import '../styles/globals.css'
import Sidebar from "../components/common/Sidebar";
import Head from "next/head";
import App from "next/app";

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://mystickermania.com/cdn/stickers/rick-and-morty/sticker_2060-512x512.png"
        />
      </Head>
      <div className="flex flex-row">
        <Sidebar />
        <Component {...pageProps} />
      </div>
    </div>
  );
}

MyApp.getInitialProps = async (appContext) => {
  // calls page's `getInitialProps` and fills `appProps.pageProps`
  const appProps = await App.getInitialProps(appContext);
  return { ...appProps };
};

export default MyApp
