import '../styles/globals.css'
import Sidebar from "../components/common/Sidebar";
import Head from "next/head";
import Image from "next/image";

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://mystickermania.com/cdn/stickers/rick-and-morty/sticker_2060-512x512.png"
        />
      </Head>
      <Sidebar />
      <Component {...pageProps} />
      <footer className="flex-1 p-8 border-t-1 border-solid justify-center align-middle">
        Powered by{" "}
        <span>
          <Image
            src="/picklerick.webp"
            alt="Pickle Rick"
            width={20}
            height={27}
          />
        </span>
      </footer>
    </div>
  );
}

export default MyApp
